version: "3"
volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  airflow-postgres-db-volume: {}
  es_data: {}

services:
  flower:
    build:
      dockerfile: ./compose/local/django/Dockerfile
      context: .
    command: celery flower
    depends_on:
      - rabbit
      - postgres
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    ports:
      - 5555:5555
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:5555/" ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  postgres:
    image: postgres:12
    restart: unless-stopped
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust

  django:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      target: app
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: drf_playground_local_django
    restart: unless-stopped
    container_name: drf-playground-django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ~/.aws/temp_env
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start
  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
        - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
        - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
        - "5672:5672"
  celery-worker:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      target: django_worker
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: drf_playground_local_django_worker
    restart: unless-stopped
    container_name: drf_playground-django-celery-worker
    volumes:
      - .:/app:z
    env_file:
      - ~/.aws/temp_env
      - ./.envs/.local/.django
    links:
      - rabbit
    depends_on:
      - rabbit
      - postgres
    command: celery -A project worker -c2 -Ofair -Q celery,long_tasks,short_tasks,courier_tasks
