version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  rabbit_mq_etc: {}
  rabbit_mq_logs: {}
  rabbit_mq_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: drf_playground_production_django
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: drf_playground_production_postgres
    restart: unless-stopped
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: drf_playground_production_traefik
    restart: unless-stopped
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"
  redis:
    image: redis:5.0
    restart: unless-stopped

  { %- if cookiecutter.use_adminer == 'y' % }
  adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - 8082:8080
  { % endif % }

  celeryworker:
    <<: *django
    image: drf_playground_production_celeryworker
    restart: unless-stopped
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: drf_playground_production_celerybeat
    restart: unless-stopped
    command: /start-celerybeat

  flower:
    <<: *django
    image: drf_playground_production_flower
    restart: unless-stopped
    command: /start-flower
