# Generated by Django 3.1.3 on 2021-07-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="name",
            field=models.CharField(default="", max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name="file",
            name="permissions",
            field=models.CharField(default="644", max_length=3, null=True),
        ),
    ]
